version: "3.8"
networks:
  net-dub-videos:

services:
  front:
    build: ./DubVideosFrontEnd
    ports:
      - "8000:8000"
    networks:
      - net-dub-videos
  main_api:
    build: ./main-dub-videos-api
    ports:
      - "5000:5000"
    depends_on:
      - transcription
      - speech
    env_file:
      - .env
    networks:
      - net-dub-videos
  transcription:
    build: ./transcription-api
    ports:
      - "5001:5001"
    container_name: dub_videos_transcription
    env_file:
      - .env
    networks:
      - net-dub-videos
  speech:
    build: ./text-to-speech-api
    ports:
      - "5002:5002"
    container_name: dub_videos_speech
    networks:
      - net-dub-videos